### PR TITLE
Toast component

### PR DESCRIPTION
**Pull request by adith-a-danthi**
## Overview
- Add toast component
  - Simple Toast
  - Bordered Toast
- Update sidebar links
- Update media query breakpoints for sidebar

Preview Link: https://deploy-preview-12--tidle-ui.netlify.app/docs/components/toast/toast.html

### CODE REVIEW

**Comment by reubenjnazareth** [comment]
Good job. Looks good to merge.

**Review by Megha-Joshi — APPROVED** [review]
Good to merge.

**Review by reubenjnazareth — APPROVED** [review]
Good job. Looks good to merge.

**Review by khushijohri2001 — COMMENTED** [review]
Code looks clean and fine to me👍

**Pull request merged**
